### ISSUE TITLE
why md5

### ISSUE THREAD

**Issue by n0way0ut** [salesforce/ja3#2]
it is really cool. Just a question: why md5 and not a faster hash like SipHash or BLAKE2?

**Comment by jalthouse-sfdc** [comment]
Thanks! Compatibility is reason for going with MD5, everything supports it, meaning JA3 can more easily be added to existing technologies.

**Comment by ilyaglow** [comment]
So by choosing md5 we are just neglecting the fact that our ”good”
hashes and deliberately generated malicious ones may have collisions?

**Comment by jalthouse-sfdc** [comment]
Given the limited data set a hash collision would be exceptionally rare, somewhere in the neighborhood of winning the lottery twice in a row. If someone were to try to manipulate a TLS Hello packet to create a MD5 hash collision as a means of getting around JA3, they're doing it wrong.

**Comment by jabedude** [comment]
@jalthouse-sfdc just curious, from an attacker perspective couldn't it make some sense to try to match well known JA3 hashes?

**Comment by neslog** [comment]
SHA256 could easily be added to extend telemetry. There have been
techniques to craft custom hello packets to mimic “known” clients.  For
those, look at combining with process information.

**Comment by jalthouse-sfdc** [comment]
> @jalthouse-sfdc just curious, from an attacker perspective couldn't it make some sense to try to match well known JA3 hashes?
@jabedude 

@neslog is correct, this already exists. However, the method they use modifies the TLS Hello packet to match that of the client they are trying to mimic. So even if you used SHA256 or fuzzy hashing, it would come out the same. So changing the hashing algorithm doesn't help in those cases, the best thing to use then is Bro-Sysmon or Zeek-OSQuery to match up the process to the JA3.
