### ISSUE TITLE
ja3.py: map does not remove items

### ISSUE THREAD

**Issue by DidierStevens** [salesforce/ja3#22]
In ja3.py, line 256:

map(remove_items,output)

It does not actually remove items, because map returns an iterator that is not consumed.
Possible solution:
list(map(remove_items,output))

**Comment by sysopfb** [comment]
Yup for python3, also need to account for the bytes type in python3. I originally wrote the code purely for python2 but fixed it shouldn't be a big deal.

            list(map(remove_items,output))
 and
                      "client_hello_pkt": binascii.hexlify(tcp.data).decode('utf-8')}

Seems to work for both python 2.7 and python 3

**Comment by jalthouse-sfdc** [comment]
Merged. Thanks! Sorry it took a while, I need to change my notifications :/
