### ISSUE TITLE
Producing the same value

### ISSUE THREAD

**Issue by omergunal** [salesforce/ja3#41]
Ja3  always producing the same value. I have 2 different pcap. they have different random bytes value.

https://ibb.co/D7gp7Dt
https://ibb.co/qx3vbc0

But it creating the same JA3 value.

```
"ja3": "771,60-47-61-53-5-10-49191-49171-49172-49195-49187-49196-49188-49161-49162-64-50-106-56-19-4,65281-0-10-11-13,23-24,0",
        "ja3_digest": "4d7a28d6f2263ed61de88ca66eb011e3"
```

**Comment by jalthouse-sfdc** [comment]
Random byte values are ignored. This appears to be the same application communicating each time and therefor has the same JA3 value each time.
