### ISSUE TITLE
Add Rust implementation to the README

### ISSUE THREAD

**Issue by jabedude** [salesforce/ja3#49]
Hello! I created a Rust implementation of your amazing work here: https://github.com/jabedude/ja3-rs.

Is there any way you could add that to your README? There is some network analysis work being done with rust in the Suricata project that might want to use it !

**Comment by tstallings** [comment]
Nice work! Added a link to the README. Now I have a good excuse to go play with Rust a bit :)

**Comment by jabedude** [comment]
thanks!
