### ISSUE TITLE
JA3(s) can not parse  windows/x64/meterpreter/reverse_https Payload

### ISSUE THREAD

**Issue by Epicccal** [salesforce/ja3#65]
Hello , When I use JA3(S) to parse MetaSploit-Framework(6.0.37-dev) - **windows/x64/meterpreter/reverse_https** Payload, it does not work.

![msf_https](https://user-images.githubusercontent.com/34046030/117230956-c3c4bf80-ae50-11eb-9258-69bf4616cce9.png)

![2021-05-06_09-53](https://user-images.githubusercontent.com/34046030/117231068-01294d00-ae51-11eb-9aee-9164ff200941.png)

I don't understand the reason for this, could you give me some suggestions? Thank you very much～

[msf_https.pcap.zip](https://github.com/salesforce/ja3/files/6431276/msf_https.pcap.zip)

**Comment by Epicccal** [comment]
Sorry, I think I found the problem. I need to specify the -a parameter because the default port for meterpreter communication is 4444。

![2021-05-06_10-35](https://user-images.githubusercontent.com/34046030/117234066-e063f600-ae56-11eb-9f99-6398e164fcbd.png)

![2021-05-06_10-35_1](https://user-images.githubusercontent.com/34046030/117234082-e4901380-ae56-11eb-8faa-e73978bd0785.png)

**Comment by Jackson-Pollock** [comment]
@Epicccal How do you performed attack?

**Comment by Jackson-Pollock** [comment]
@Epicccal Just one question, How did you performed this attack? The msfvenom binary with ..reverse_https payload and listener on other end, that's it right?
