### ISSUE TITLE
Will you add this to the Bro Package Manager system?

### ISSUE THREAD

**Issue by swedishmike** [salesforce/ja3#8]
Hey guys,

Thanks for providing this - it looks awesome and I can really see the usefulness of it in my own deployment.

One quick question - do you have any plans to integrate it with the Bro Package Manager system (http://bro-package-manager.readthedocs.io/en/stable/index.html)? It simplifies deployment and maintenance on the hosts quite a bit.

Thanks in advance, Mike

**Comment by mdtro** [comment]
I'll second this. I would love to see ja3 in the Bro Package Manager.

**Comment by jalthouse-sfdc** [comment]
You got it!
