### ISSUE TITLE
Rename the project to something meaningful!

### ISSUE THREAD

**Issue by WilliamSalusky** [salesforce/ja3#9]
STFU - SSL / TLS Fingerprinting Uniqueness
STUF - SSL / TLS Unique Fingerprinting
STF   -  SSL / TLS Fingerprinting

:trollface: seriously!

**Comment by jalthouse-sfdc** [comment]
Where were you when we were working on this, W!?

In the future we'll roll up all the tech into a SSL / TLS Fingerprinting Utility.
